name: Test Locally

on: [push]

jobs:
  run-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "Running GitHub Action locally!"
