name: Trigger Jenkins Job from GitHub

on:
  push:
    branches:
      - main  # Replace with your target branch

jobs:
  trigger-jenkins:
    runs-on: self-hosted

    steps:
      - name: Trigger Jenkins via REST API
        run: |
          curl -X POST "$JENKINS_URL/job/$JENKINS_JOB_NAME/build?token=$JENKINS_TRIGGER_TOKEN" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN"
        env:
          JENKINS_URL: 'http://:8080'
          JENKINS_USER: ''
          JENKINS_API_TOKEN: ''
          JENKINS_JOB_NAME: 'Freestyle-project'
          JENKINS_TRIGGER_TOKEN: 'trigger-from-github'
          # JENKINS_URL: 'http://localhost:8080'
          # JENKINS_USER: 'KankanD1024'
          # JENKINS_API_TOKEN: '11190b66c8b14c4afcb53be61bf302048b'
          # JENKINS_JOB_NAME: 'Freestyle-project'
          # JENKINS_TRIGGER_TOKEN: 'trigger-from-github'
